# Generated by Django 6.1.1 on 2026-10-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('geo_precision', models.CharField(default='city', max_length=20)),
                ('popularity', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lon'], name='stations_st_lat_91f89c_idx')],
            },
        ),
    ]
